version: '2'
services:
  proxy:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "9001:8080"
    volumes:
      - ./proxy/custom.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
  # We are using built default image of Golang app from assigment 2
    image: go-app-def
    ports: 
      - "8080"


